sudo: required
dist: trusty
language: python

python:
  - "3.6"

install:
  # code below is taken from http://conda.pydata.org/docs/travis.html
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
    
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pandas pytest h5py Pillow
  - source activate test-environment
  
  # Upgrading libgcc to prevent an error when running the tests (see https://github.com/tensorflow/tensorflow/issues/5017#issuecomment-295566267)
  - conda install libgcc
  - conda update -f libstdcxx-ng
  - conda install -c anaconda tensorflow
  
  # Install additional requirements
  - pip install https://download.pytorch.org/whl/cpu/torch-1.0.0-cp36-cp36m-linux_x86_64.whl  
  - pip install -r ModelGenerator-tensorflow/requirements.txt
  - pip install -r ModelGenerator-pytorch/requirements.txt

script:
  - pytest --cov=./
  - cd ModelGenerator-pytorch
  - pytest --cov=./ -s

after_success:
  - codecov